### ISSUE TITLE
Current status of the SDK

### ISSUE THREAD

**Issue by Survikrowa** [logto-io/react-native#16]
Hi! 
Will u continue the work on this SDK since the required bugfix has been live since 2022? Or is there any other way to use logto in expo?

**Comment by charIeszhao** [comment]
Hi, thanks for asking.

Yes, the work has been continued, and @gao-sun just posted [a step-by-step tutorial](https://blog.logto.io/expo-react-native/) on our blog site.

You can check it out and let us know if it works for you.
