### ISSUE TITLE
bug: After signing in, error thrown where `atob` doesn't exist

### ISSUE THREAD

**Issue by alwyntan** [logto-io/react-native#21]
### Describe the bug
After signing in, error thrown where `atob` doesn't exist

### Expected behavior
No error to be thrown and the idToken to be properly decoded on the frontend.

### How to reproduce?
Install `@logto/rn` and set it up correctly, then run the `signIn` with a valid user.

### Context
- [x ] Logto Cloud
- [ ] Self-hosted, Logto version = 
  - [ ] Container (Docker image)
  - [ ] Raw Node.js

### Screenshots
![simulator_screenshot_99E82260-D3F8-49A2-B283-1E814759214D](https://github.com/logto-io/react-native/assets/19474611/3947ec64-abf6-473b-81c6-7e07aba72763)

**Comment by alwyntan** [comment]
React native should be adding the window.atob to hermes soon (expected in 0.74), as seen in https://github.com/facebook/hermes/issues/1178, but that will be a while.

A known approach to fix this for now is to use the `Base64` library, and call the `Base64.atob` function instead

**Comment by gao-sun** [comment]
Can you try to import the polyfill for now?

`import '@logto/rn/polyfill';`
