### ISSUE TITLE
bug:  getAccessToken not result the string likely not accessToken 

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [logto-io/react-native#37]
### Describe the bug
 -> Result of function  getAccessToken() => AccessToken: "eIEm5vf6IoAOzgn4CMkXjsl6jpbWSt0Ffsx-uRIZGxT"
-> it not me Expected string 

### Expected behavior
-> Result of function  getAccessToken() => AccessToken: "eIEm5vf6IoAOzgn4CMkXjsl6jpbWSt0Ffsx-uRIZGxT"
-> it shoult be longer string and able to use for request api from `https://<endpoint-resourse>/api/v1`

### How to reproduce?
```

import { Button, Text } from "react-native";

import {
  LogtoConfig,
  LogtoProvider,
  Prompt,
  ReservedScope,
  useLogto,
  UserScope,
} from "@logto/rn";

import { useEffect, useState } from "react";

const RenderContent = () => {
  const { signIn,signOut,getAccessToken,isAuthenticated,getIdTokenClaims,} = useLogto();
  const [user, setUser] = useState(null);
  const [at, setAT] = useState(null);

  useEffect(() => {
    if (isAuthenticated) {
      getAccessToken().then((accessToken) => {
        setAT(accessToken);
      });
      getIdTokenClaims().then((claims) => {
        setUser(claims);
      });
    }
  }, [isAuthenticated]);

  return (
    <View style={{ paddingTop: 100 }}>
      {isAuthenticated ? (
        <View>
          <Text>{`AccessToken: ${JSON.stringify(at, undefined, 2)}`}</Text>
          <Text>{`\n--------------------------\n`}</Text>
          <Text>{`User Info: ${JSON.stringify(user, undefined, 2)}`}</Text>
          <Button title="Sign out" onPress={async () => signOut()} />
        </View>
      ) : (
        <Button
          title="Sign In"
          onPress={() =>
            signIn({
              redirectUri: "io.logto://callback",
              loginHint: "email@test.com",
            })
          }
        />
      )}
    </View>
  );
};

const logtoConfig: LogtoConfig = {
  appId: "lx2l0yq69d9q9p8u4xtbt",
  endpoint: "https://<endpoint>/",
  resources: ["https://<endpoint-resourse>/api/v1"],
  scopes: [
    UserScope.CustomData,
    UserScope.Email,
    UserScope.Identities,
    UserScope.OrganizationRoles,
    UserScope.Organizations,
    UserScope.Phone,
    UserScope.Profile,
    UserScope.Roles,
  ],
  includeReservedScopes: false,
};

export default function App() {
  return (
    <LogtoProvider config={logtoConfig}>
      <RenderContent />
    </LogtoProvider>
  );
}
```

### Context
React-native - almost all using are lastest version
"react-native": "0.76.3", 
"@logto/rn": "^0.4.0",
"expo": "^52.0.0",
"expo-crypto": "~14.0.1",
"expo-secure-store": "~14.0.0",
"expo-web-browser": "~14.0.1",

- [ ] Logto Cloud
- [x ] Self-hosted, Logto version = [v1.21.0](https://github.com/logto-io/logto/releases/tag/v1.21.0) 
  - [x ] Container (Docker image)
  - [ ] Raw Node.js

**Comment by darcyYe** [comment]
This is not a bug, should specify `resource` when calling `getAccessToken(resourceIndicator)` in order to get JWT-format token.

**Comment by NguyenHoangMinhkkkk** [comment]
> This is not a bug, should specify `resource` when calling `getAccessToken(resourceIndicator)` in order to get JWT-format token.

Hi, thanks for look at my issue. 

The error catched ``LogtoClientError: Not authenticated.`` after i put the resource in.

        getAccessToken( logtoConfig.resources[0] ) // resource here
          .then((accessToken) => {
            console.log(
              "==========accessToken-accessToken=======",
              accessToken
            );
            if (accessToken) setAT(accessToken);
          })
          .catch((e) => {
            console.log("==========catch-catch=======", e);  // LogtoClientError: Not authenticated.
          });

**Comment by darcyYe** [comment]
You should specify the resource in authentication flow, e.g. include `resource` in `signIn()` method.
The error message clearly shows that the resource is not authenticated. If the error still happens, you should double check whether a `scope` (associate to the wanted `resource`) is assigned to the user, and make sure you have explicitly specify the scope and resource in `signIn()` method.

**Comment by nickdaugherty** [comment]
`signIn()`'s `SignInOptions` [doesn't have a `resource` property,](https://github.com/logto-io/js/blob/a0f91a3acf84c34eac6fa5b89348896a8ea2bfe4/packages/client/src/client.ts#L40-L58) did you mean `resources` from `LogtoConfig`? 

Either way, setting `resources` in the provider config and calling `getAccessToken( resourceId )` still returns the not authenticated error. Something seems broken here.

**Comment by nickdaugherty** [comment]
@NguyenHoangMinhkkkk it seems to work if you only set the resource id in `resources` in the Logto config (but not in the `getAccessToken()` call.

**Comment by nickdaugherty** [comment]
I finally figured this out. `getAccessToken()` will fail with the "Not authenticated" error if there is no `refreshToken` saved to storage. (This error is not very clear).

In Logto, Native Apps don't have the "always issue refresh token" setting that other app types do, which might lead you to think that refresh tokens will always be issued, but that's not the case. Refresh tokens are not issued by default upon authentication, which means you can't get an access token for your resources by default 🙃 .

To get a refresh token and then an access token, you have to send the "consent" prompt in the `signIn()` call:

```
signIn({
    redirectUri: ...
    prompt: [Prompt.Login, Prompt.Consent],
})
```

**Comment by obukhov** [comment]
This seems to be extremely counterintuitive and not documented anywhere? @nickdaugherty are you sure that's a proper fix ? What does prompt has to do with refresh token? Even in "sample app" they have "Login" flow
